build: Fix windows build on newer MSVC
osquery/osquery pull request #6725
Opened 2020-10-23 14:48 UTC by sharvilshah

Windows build was broken on newer MSVC:
It couldn't find the `random_shuffle` identifier:

```
TSocketPool.cpp(191): error C3861: 'random_shuffle': identifier not found 
```

Turns out we weren't quoting things properly to include the `random_shuffle.h` patch. 
Hat tip to @Smjert for figuring that out.

cc: @muffins

2020-10-23 15:12 UTC, sharvilshah commented
This is now breaking on Linux and macOS, looking...

2020-10-23 15:12 UTC, closed without merging

2020-10-23 15:12 UTC, muffins approved these changes
Lgtm! Thanks for the quick fix!

2020-10-23 15:13 UTC, muffins requested changes
Ah didn't see your note about the breakages, feel free to dismiss my review!

2020-10-23 15:14 UTC, sharvilshah commented
Ah, I broke the other platforms (and older msvc) lol. Looking into it, will update and reopen.

2020-10-23 17:42 UTC, Smjert commented
@sharvilshah Try with `"SHELL:${forced_include_file_flag} ${CMAKE_CURRENT_SOURCE_DIR}/patches/random_shuffle.h"`

2020-10-26 16:12 UTC, sharvilshah commented
Thanks for the suggestion @Smjert, but that too couldn't find `random_shuffle` identifier :(
I have just set `forced_include_file_flag` based on the platform (in new PR, I forced pushed and can't reopen this one)