Add new table location_services for darwin
osquery/osquery pull request #6826
Opened 2020-12-20 17:39 UTC by terracatta

### What does this new table do?
This table consists of only one column that reports the enabled/disabled status of the Location Services feature of macOS. See screenshots below.

#### Location Services Enabled
<img width="1063" alt="Screen Shot 2020-12-20 at 12 33 23 PM" src="https://user-images.githubusercontent.com/315873/102720052-dc787280-42bf-11eb-81ff-3c20ccca1c68.png">

#### Location Services Disabled
<img width="1059" alt="Screen Shot 2020-12-20 at 12 33 57 PM" src="https://user-images.githubusercontent.com/315873/102720056-dedacc80-42bf-11eb-979c-b5fc54bc707e.png">

### Why is this useful?
There are many people for compliance and privacy reasons who need to understand the current state of Location Services.

### Other Notes

1. I added a new framework to get this data (Corelocation), the framework has been around since 10.6 so we should be safe, but we might want to verify older macOS compatibility just to be sure the API hasn't changed.

1. I kept the table simple as I imagine this would be something we could extend to Windows.

1. This API does not pass any errors by reference so I just threw it in a Try/Catch block just in case we have issues, not sure if that is an acceptable pattern for such a simple class method API.

2020-12-20 21:11 UTC, theopolis requested changes

2020-12-20 21:11 UTC, theopolis commented on osquery/tables/system/darwin/location_services.mm
> +        << "[CLLocationManager locationServicesEnabled]: threw exception "
Do you mind making this error a bit less developer-friendly and more general user friend? Perhaps: `"CoreLocation API locationServicesEnabled threw exception: " << exception.name`

2020-12-20 21:11 UTC, theopolis commented on osquery/tables/system/darwin/location_services.mm
> +namespace fs = boost::filesystem;
I do not think you need this namespace alias?

2020-12-20 21:12 UTC, theopolis commented
The pattern feels reasonable. Do you mind adding an integration test too?

2020-12-20 21:52 UTC, terracatta commented
> The pattern feels reasonable. Do you mind adding an integration test too?

Sure!

2020-12-21 15:54 UTC, theopolis approved these changes

2020-12-21 18:37 UTC, mike-myers-tob commented
Nice. :+1: 

I didn't realize there was a testing helper function `validate_rows`!

2020-12-21 18:37 UTC, merged