Move packaging logic to osquery-packaging
osquery/osquery pull request #6921
Opened 2021-01-25 21:34 UTC by alessandrogario

2021-01-29 16:00 UTC, theopolis commented
We definitely need to document why this change is happening. And we need to update the docs with instructions on how to build packages.

2021-02-05 02:50 UTC, theopolis requested changes

2021-02-05 02:50 UTC, theopolis commented on docs/wiki/development/building.md
> +```batch
Double check this file to make sure there are empty newlines between statements and code sections.

2021-02-05 02:50 UTC, theopolis commented on docs/wiki/development/building.md
> +Common input parameters
Empty newline before and after this

2021-02-05 02:50 UTC, theopolis commented on docs/wiki/development/building.md
> +Linux-specific parameters:
Empty newline after this

2021-02-05 02:50 UTC, theopolis commented on docs/wiki/development/building.md
> + - **CPACK_GENERATOR**: Either `WIX` or `NuGet`
ditto

2021-02-05 02:50 UTC, theopolis commented on docs/wiki/development/building.md
> +### Creating the macOS packages
ditto before

2021-02-05 02:50 UTC, theopolis commented on docs/wiki/development/building.md
> + - **CPACK_GENERATOR**: Either `productbuild` (PKG  files) or `TGZ`
ditto

2021-02-05 15:28 UTC, theopolis submitted a review, later dismissed

2021-02-09 03:46 UTC, directionless submitted a review, later dismissed
At least on macOS, this does produce a `package_data`, which is awesome.

Some nits/suggestions, both of which are not blocking:
1. This build should leave a VERSION file. The packaging consumer should not need the to find the version
2. I want to quibble about the structure in `package_data` -- on macOS, there are 3 directories. `control`, `private`, and `usr`. I'm pretty sure the first is a meta directory, and the latter two are in `/`. I feel like convention would be to create `control` and `root`.

Anyhow, quibbles.

2021-04-06 03:03 UTC, directionless approved these changes

2021-04-07 01:35 UTC, theopolis requested changes

2021-04-07 01:35 UTC, theopolis commented on .github/workflows/build.yml
> -        echo ::set-output name=DEB_PACKAGE_NAME::$(ls *.deb)
I think you need to update these variables below (lines 449, etc). I believe this is the cause of the build failures on Linux.

2021-04-15 01:21 UTC, theopolis commented
This looks good but heads up it has not updated the `build_aarch64` workflows. Those will start to fail after this is merged. Do you want to update them in the same PR or let them break and follow up with another PR.

A good way to test them is to develop in a feature branch on `osquery/osquery`.

2021-04-15 09:17 UTC, alessandrogario commented
> This looks good but heads up it has not updated the `build_aarch64` workflows. Those will start to fail after this is merged. Do you want to update them in the same PR or let them break and follow up with another PR.
> 
> A good way to test them is to develop in a feature branch on `osquery/osquery`.

I was wondering how to test this, as I would have preferred to not break the AArch64 workflow; I'll create a new branch and switch my PR to work against it

2021-04-15 09:48 UTC, merged