Improve docs on FIM, mention NTFS and Audit, etc.
osquery/osquery pull request #7036
Opened 2021-04-02 02:07 UTC by mike-myers-tob

The FIM docs needed some attention. They're out of date and didn't mention Audit-based FIM or NTFS Journal Events -based FIM. Users often have trouble setting it up.

2021-04-02 13:34 UTC, directionless submitted a review, later dismissed
Nice additions

2021-04-07 01:45 UTC, theopolis requested changes
Thanks so much for the effort here, this is outstanding!

2021-04-07 01:45 UTC, theopolis commented on docs/wiki/deployment/file-integrity-monitoring.md
> +FIM is also disabled by default in osquery. To enable it, first ensure that events are enabled in osquery (`--disable_events=false`), then ensure that the desired FIM table is enabled with the corres
```suggestion
FIM is also disabled by default in osquery. To enable it, first ensure that events are enabled in osquery (`--disable_events=false`), then ensure that the desired FIM table is enabled with the corresponding CLI flag (`--enable_file_events=true` for `file_events`, `--disable_audit=false` for `process_file_events`, `--enable_ntfs_publisher=true` for `ntfs_journal_events`).
```

2021-04-07 01:45 UTC, theopolis commented on docs/wiki/deployment/file-integrity-monitoring.md
> +- With iNotify, moving a directory of directories into a watched directory does not immediately add all of those subdirectories to the watched set. [Issue 1969](https://github.com/osquery/osquery/iss
Heads up about the inconsistent spelling of inotify, we use "inotify", "`inotify`", and "iNotify". I am unsure which is correct, but I recommend we rewrite the document to use a single forme.

2021-04-07 01:54 UTC, mike-myers-tob commented on docs/wiki/deployment/file-integrity-monitoring.md
> +FIM is also disabled by default in osquery. To enable it, first ensure that events are enabled in osquery (`--disable_events=false`), then ensure that the desired FIM table is enabled with the corres
Good catch!

2021-04-07 23:39 UTC, theopolis approved these changes

2021-04-08 01:14 UTC, merged