Support new sudo include syntax
osquery/osquery pull request #7185
Opened 2021-07-01 20:13 UTC by directionless

In sudo 1.9.1, sudo changed the include directives from `#include` to
`@include` (See
https://github.com/sudo-project/sudo/commit/741c6f274e65f852b7026b10a21dff519b2fd6c2)

Support parsing them.

Along the way, add more tests and update the parsing

2021-07-12 16:23 UTC, theopolis requested changes
A few nitpicks, then good to go

2021-07-12 16:23 UTC, theopolis commented on osquery/tables/system/posix/sudoers.cpp
> +const char* kSudoWhitespaceChars = "\t\v ";
```suggestion
const std::string kSudoWhitespaceChars = "\t\v ";
```

can this be `const std::string` for consistency (we use `std::string` for most other consts).

2021-07-12 16:23 UTC, theopolis commented on osquery/tables/system/posix/sudoers.cpp
> +    if (line.size() == 0) {
```suggestion
    if (line.empty()) {
```

2021-07-12 16:23 UTC, theopolis commented on osquery/tables/system/posix/sudoers.cpp
> +    if (rule_details == "" &&
```suggestion
    if (rule_details.empty() &&
```

2021-07-12 16:23 UTC, theopolis commented on osquery/tables/system/posix/sudoers.cpp
> +        TLOG << "couldn't list includedir: " << rule_details;
```suggestion
        TLOG << "Could not list includedir: " << rule_details;
```

2021-07-12 16:23 UTC, theopolis commented on osquery/tables/system/posix/sudoers.cpp
> +        (header == "#include" || header == "@include" ||
Nitpick but if you are checking `header` here and then below, you could optimize

```
auto is_include = (header == "#include" || header == "@include");
auto is_includedir = (header == "#includedir" || header == "@includedir");
```

Then this becomes:

```
if (rule_details.empty() && (is_include || is_include_dir)) {
```

And below is either `if (is_include)` or `if (is_includedir)`.

2021-07-13 15:09 UTC, directionless commented
Thank for the feedback! I think I got all of it. I considered making `path` a context settable variable. But that seems better left to a future PR

2021-07-13 16:10 UTC, theopolis approved these changes

2021-07-14 01:21 UTC, merged