[AWS] Optionally enable debug option and restrict content-type header size for PUT req
osquery/osquery pull request #7216
Opened 2021-07-28 16:45 UTC by sharvilshah

This PR:

* adds a `aws_enable_debugging` FLAG option, to enable AWS-SDK debug logging
* restrics header size for `content-type` in PUT requests to a reasonable length 

This fixes the `ec2_instance_tags` table, and other timeout issues with AWS PUT requests that we been seeing on an IMDSv2 enforced instance

2021-08-02 01:02 UTC, theopolis requested changes

2021-08-02 01:02 UTC, theopolis commented on osquery/utils/aws/aws_util.cpp
> +FLAG(bool, aws_enable_debugging, false, "Enable AWS SDK debug logging");
nitpick, how about `aws_debug`?

2021-08-03 10:49 UTC, sharvilshah commented on osquery/utils/aws/aws_util.cpp
> +FLAG(bool, aws_enable_debugging, false, "Enable AWS SDK debug logging");
Thanks, that sounds better, updated!

2021-08-04 00:54 UTC, theopolis approved these changes

2021-08-04 00:54 UTC, merged