Unifiedlogs api
osquery/osquery pull request #7259
Opened 2021-08-16 02:03 UTC by puffyCid

This PR fixes and address the comments on the awesome PR done by @GarretReece and others at #6904 that adds unified log parsing.  
This PR only changes a few lines from the original implmentation done at #6904 to fix the issues mentioned:
* Segfault - Should be fixed, ran multiple times over 20 million logs, no issues
* Tests - Added tests to this PR
* Website docs - I can try to open a PR for the website documentation if this PR gets merged

On Slack it was mentioned it would likely be easier to open a new PR rather than trying to edit an existing one. 

The original PR summary for #6904 is copied below for clarity
```
This code implements a virtual table for darwin that uses the OSLog framework to read and return entries from the unified system log. Prior versions of macOS did not have an api to access this data, necessitating an extension that invoked the log utility. macOS 10.15 makes this no longer necessary.

At the moment I've tested these changes only on a 10.15 vm. I'd be grateful to the community for feedback regarding building on earlier versions of macOS.

Closes #5760
```

Let me know if additional changes or improvements need to be made

2021-08-16 02:04 UTC, puffyCid commented
Also I just wanted to mention that i am also trying to implement a raw UAL parsing support to osquery at https://github.com/puffyCid/osquery/tree/unifiedlogs.  
The benefit of raw parsing is that it will support older macos versions and it is slightly more forensic focus (raw parsing vs api).
Its ~60% done and it still has lots of work to be done, but just wanted to mention it, if others want to monitor/contribute/comment.  Im slowly working/chipping away on it between other osquery features im working on.
References:
* [libyal doc](https://github.com/libyal/dtformats/blob/main/documentation/Apple%20Unified%20Logging%20and%20Activity%20Tracing%20formats.asciidoc)
* [existing example raw log parser](https://github.com/ydkhatri/UnifiedLogReader)

2021-09-02 02:47 UTC, directionless commented
> Also I just wanted to mention that i am also trying to implement a raw UAL parsing support to osquery

To respond to the side note... I know there are advantages, but parsing feels more fraught than API usage. There are going to be security and sanitization questions, and file format durability questions.

2021-09-02 22:09 UTC, puffyCid commented
> > Also I just wanted to mention that i am also trying to implement a raw UAL parsing support to osquery
> 
> To respond to the side note... I know there are advantages, but parsing feels more fraught than API usage. There are going to be security and sanitization questions, and file format durability questions.

yep very good points. Its mainly a side project/research. There is only one open source raw parser im aware of https://github.com/ydkhatri/UnifiedLogReader. 
(format docs for those curious: https://github.com/libyal/dtformats/blob/main/documentation/Apple%20Unified%20Logging%20and%20Activity%20Tracing%20formats.asciidoc)

The main reason a raw parser would be desired is mainly a forensic/investigation one. When doing forensic analysis on a system that is compromised from an analysis perspective the investigator can't really trust the OS (due to possible rootkits/malware).  And also for older macs where the api doesnt exist.
Ex: A hypothetical scenario in which a rootkit was installed on a mac and was able to manipulate the logging framework to hide log entries related to the rootkit/other malware would cause the api to not get the full data vs raw parsing the actual files would potentially be unaffected.  

Again, hypothetical, ive never seen that happen, but when doing forensic investigations ideally the data is parsed independently from the OS apis/tools (if possible).

But that being said, i think the work done by adding UAL parsing via API is awesome and will very useful for everyone!

2021-11-19 06:08 UTC, elyscape commented
Any chance of this getting some movement? This would be a really useful feature to have.

2021-11-25 03:16 UTC, puffyCid commented
@elyscape I'm currently waiting for feedback
Once the PR gets reviewed and feedback I can make changes and hopefully it will get merged

2021-12-11 15:08 UTC, alessandrogario requested changes

2021-12-11 15:08 UTC, alessandrogario commented on osquery/tables/system/darwin/unified_log.mm
> +QueryData genUnifiedLog(QueryContext& queryContext) {
A mandatory `WHERE` clause should be implemented to limit the scope of the query and avoid watchdog issues with simple `SELECT * FROM table` statements

2022-07-20 14:53 UTC, FritzX6 commented
@mike-myers-tob, @directionless,

IIRC @puffyCid is no longer part of the osquery slack and I am not sure if they are continuing to contribute to the osquery project any longer, not sure how you think it best to proceed in terms of keeping this PR from being orphaned.

2022-07-20 15:59 UTC, directionless commented
@FritzX6 This work has continued in #7598

2022-08-03 23:11 UTC, closed without merging