Set local_time column on time table to hidden
osquery/osquery pull request #7276
Opened 2021-08-21 01:49 UTC by theopolis

The concept of a "local" UNIX time is confusing since UNIX time should be counted from the epoch, which specifies a timezone.

2021-08-21 05:52 UTC, sharvilshah approved these changes

2021-08-22 15:09 UTC, directionless commented
i won't block this -- but if you can please hold up? I want to try to understand what the intent here had been

2021-08-22 15:27 UTC, theopolis commented
Check out @Smjert's analysis in the linked issue here: https://github.com/osquery/osquery/issues/7274

2021-08-22 20:04 UTC, directionless requested changes
I spent a bit staring at this, and trying to understand the past. Notable here is #2504 which claimed to remove local time. And @Smjert's writeup 

Given that this is landing in 5.0, I think we should be more extensive -- if we think the column does nothing, we should simply drop it and be done. It doesn't seem worth carrying the baggage forward. I think we should also drop the `timezone` column. Or merge it with local_timezone. Or whatever. 

My read on `--utc` is that it adjust the human readable parts of the time table to utc vs local time. I think there's value there, but that the help on the flag should be updated. The whole human readable thing feels a little duplicated with the sqlite time functions, but :shrug: it seems fine.

2021-08-24 03:19 UTC, theopolis commented
I agree with that analysis and I'll make some changes to be more "breaking". I think removing the `--utf` flag is best and going with the SQLite time functions is the most universal.

2021-08-24 03:28 UTC, theopolis commented
I opted to keep `"timezone"` to indicate that the human-readable columns here referred to time in UTC.

2021-08-24 04:07 UTC, directionless commented on specs/utility/time.table
>      Column("timezone", TEXT, "Current timezone in the system"),
This is now hardcoded, not the system timezone. I'd probably change the desc of all of these, they're not system time. They're in UTC

2021-09-08 16:34 UTC, sharvilshah submitted a review, later dismissed

2021-09-08 16:34 UTC, sharvilshah commented on specs/utility/time.table
> +    Column("month", INTEGER, "Current month in UTC),
@theopolis This is missing an ending `"` in `"Current month in UTC` (that's also the reason the build is failing)

2021-09-09 17:08 UTC, mike-myers-tob commented
Moving this to 5.1 because we want to get 5.0.1 out. As discussed in Slack recently. :-)

2021-11-03 14:28 UTC, theopolis commented
@directionless and @sharvilshah, ready for review and merge?

2021-12-23 03:04 UTC, directionless commented on specs/utility/time.table
> +    Column("timezone", TEXT, "Current timezone in UTC"),
```suggestion
    Column("timezone", TEXT, "Timezone for reported time(UTC)"),
```

2021-12-23 03:04 UTC, directionless reviewed
Small nit, though I'd take it either way

2021-12-24 20:27 UTC, directionless commented
(Trigger a new ci build)

2021-12-26 04:11 UTC, directionless approved these changes

2021-12-26 20:51 UTC, merged