docs: remove FreeBSD
osquery/osquery pull request #7508
Opened 2022-03-16 18:38 UTC by sharvilshah

Removes FreeBSD mentions from README and readthedocs

2022-03-17 16:45 UTC, Smjert requested changes
Thanks for the PR!

There are another couple of places that I mentioned above in the wiki, otherwise looks good!

2022-03-17 16:45 UTC, Smjert commented on docs/wiki/index.md
> +osquery is an operating system instrumentation framework for Windows, OS X (macOS), and Linux. The tools make low-level operating system analytics and monitoring both performant and intuitive.
There's more also here
https://github.com/osquery/osquery/pull/7508/files#diff-6872e0acfa62253b9d51742be4907abc9d74cb0de73ff33ef4e3346bc2f8c9ddR7

and here
https://github.com/osquery/osquery/pull/7508/files#diff-6872e0acfa62253b9d51742be4907abc9d74cb0de73ff33ef4e3346bc2f8c9ddR11

2022-03-21 21:18 UTC, Smjert approved these changes

2022-03-22 02:30 UTC, directionless approved these changes

2022-03-28 17:41 UTC, merged