add user_data=True for screenlock table
osquery/osquery pull request #7649
Opened 2022-06-24 03:35 UTC by zhumo

To submit a PR please make sure to follow the next steps:

- [ ] Read the `CONTRIBUTING.md` guide at the root of the repo.
- [ ] Ensure the code is formatted building the `format_check` target.  
      If it is not, then move the committed files to the git staging area,
      build the `format` target to format them, and then re-commit.
      [More information is available on the wiki](https://osquery.readthedocs.io/en/latest/development/building/#formatting-the-code).
- [ ] Ensure your PR contains a single logical change.
- [ ] Ensure your PR contains tests for the changes you're submitting.
- [ ] Describe your changes with as much detail as you can.
- [ ] Link any issues this PR is related to.
- [ ] Remove the text above.

2022-06-24 17:17 UTC, Smjert requested changes
@zhumo @directionless This only adds a warning to pass the user as constraint, but the table is not actually implementing the logic.

2022-06-24 18:41 UTC, zhumo commented
Yikes. I won't know how to do that. 

So does this mean we don't need this doc change and the table is working fine as is? Or does this mean, someone should implement this functionality in the table?

2022-06-24 20:08 UTC, Smjert commented
> Yikes. I won't know how to do that.
> 
> So does this mean we don't need this doc change and the table is working fine as is? Or does this mean, someone should implement this functionality in the table?

Well, I think it's a matter of what is the expected behavior?
On my macbook with 12.4 this seems to work fine, I can see it detect it's enable and grace period is 0, but was the expectation that one could read the settings for another user on the same machine or?
This is totally missing from the table (and anyway, it seems from your report that this is not possible anymore anyway).

2022-07-03 01:41 UTC, directionless commented
This table is kinda magic, I think we documented it in the original PR.  Basically, the underlying library needs to run in a user's context. And the only way we've found to get it, is `launchd runas`.  So there's no simple way, inside osquery, to pass a uid in.

2022-07-03 15:54 UTC, Smjert commented
> This table is kinda magic, I think we documented it in the original PR. Basically, the underlying library needs to run in a user's context. And the only way we've found to get it, is `launchd runas`. So there's no simple way, inside osquery, to pass a uid in.

Oh I see, I realize now that I did the test incorrectly, because I was not running osquery via launchd, which I presume is what causes the issue, but I was launching it from terminal or using sudo.
There's something similar on Windows where there are some registry hives (of other users) that you cannot access unless you're logged in with that user.

I know we currently have some functionality that attempts to "drop" privileges (and sometimes actually change the osquery user to another user, not nobody), but it doesn't seem to fully work on macOS, only the `gid` gets changed, and the `uid` remains root (0).

2022-07-03 18:52 UTC, directionless commented
> I wonder if there's another way and if that would somehow solve the issue, or if you really need something else to be initialized as that user.

Dunno. `launchd runas` was the only thing we found. The user also has to have been recently logged in, so the underlying data is decrypted and available

2022-07-05 18:30 UTC, mike-myers-tob commented
It sounds like this PR may not improve the confusion around user context-specific tables. Does someone want to open a blueprint issue and maybe it can be added to the table specs or highlighted somehow in a new way? The user-context-specific problem is a big one for osquery but maybe there's a way to make it less confusing for users.

2022-07-13 19:58 UTC, zhumo commented
Alright, I tried one more time to capture somewhat tersely what was discussed above.

2022-08-01 19:19 UTC, zhumo commented
@Smjert @directionless Hello! wanted to ping you all again here... WDYT?

2022-08-02 13:06 UTC, directionless approved these changes

2022-08-02 17:10 UTC, Smjert commented
Closing and reopening to update the CI logic.

2022-08-02 19:01 UTC, merged