Allow querying of kernel and filesystem drivers
osquery/osquery pull request #8119
Opened 2023-08-23 23:56 UTC by joshdhart

Fix issue [6852](https://github.com/osquery/osquery/issues/6852)

Windows "Services" can be created as drivers too. 
Currently osquery has no way to query info about File System Drivers or Kernel Drivers that are registered as "Services".
As the "drivers" table, rightly only includes Device Drivers. 

Local testing done:
```
C:\Source\osquery\build\osquery\RelWithDebInfo>osqueryi.exe "SELECT * FROM services WHERE name LIKE 'wof';"
+------+--------------------+-------------------------------------------+---------+-----+------------+-----------------+-------------------+------+-------------+-------------+--------------+
| name | service_type       | display_name                              | status  | pid | start_type | win32_exit_code | service_exit_code | path | module_path | description | user_account |
+------+--------------------+-------------------------------------------+---------+-----+------------+-----------------+-------------------+------+-------------+-------------+--------------+
| Wof  | FILE_SYSTEM_DRIVER | Windows Overlay File System Filter Driver | RUNNING | 0   | BOOT_START | 0               | 0                 |      |             |             |              |
+------+--------------------+-------------------------------------------+---------+-----+------------+-----------------+-------------------+------+-------------+-------------+--------------+

C:\Source\osquery\build\osquery\RelWithDebInfo>osqueryi.exe "SELECT * FROM services WHERE name LIKE 'ws2ifsl';"
+---------+---------------+-----------------------------------------------------------------+---------+-----+--------------+-----------------+-------------------+------------------------------------------+-------------+--------------------+--------------+
| name    | service_type  | display_name                                                    | status  | pid | start_type   | win32_exit_code | service_exit_code | path                                     | module_path | description        | user_account |
+---------+---------------+-----------------------------------------------------------------+---------+-----+--------------+-----------------+-------------------+------------------------------------------+-------------+--------------------+--------------+
| ws2ifsl | KERNEL_DRIVER | Windows Socket 2.0 Non-IFS Service Provider Support Environment | RUNNING | 0   | SYSTEM_START | 0               | 0                 | \SystemRoot\system32\drivers\ws2ifsl.sys |             | Winsock IFS Driver |              |
+---------+---------------+-----------------------------------------------------------------+---------+-----+--------------+-----------------+-------------------+------------------------------------------+-------------+--------------------+--------------+

C:\Source\osquery\build\osquery\RelWithDebInfo>osqueryi.exe "SELECT count(*) FROM services;"
+----------+
| count(*) |
+----------+
| 619      |
+----------+

C:\Source\osquery\build\osquery\RelWithDebInfo>osqueryi.exe "SELECT count(*) FROM services WHERE service_type LIKE '%PROCESS%';"
+----------+
| count(*) |
+----------+
| 252      |
+----------+

C:\Source\osquery\build\osquery\RelWithDebInfo>osqueryi.exe "SELECT count(*) FROM services WHERE service_type LIKE '%DRIVER%';"
+----------+
| count(*) |
+----------+
| 367      |
+----------+

C:\Source\osquery\build\osquery\RelWithDebInfo>osqueryi.exe "SELECT count(*) FROM services WHERE service_type LIKE 'unknown';"
+----------+
| count(*) |
+----------+
| 0        |
+----------+
```

- [?] Ensure your PR contains tests for the changes you're submitting.
    - all tests for the services table seem disabled.  https://github.com/osquery/osquery/blob/master/tests/integration/tables/services.cpp

2023-08-24 14:24 UTC, sharvilshah requested changes
hey @joshdhart thanks for the PR! can you please run `clang-format` on the file? Once that check passes, that will make the CI trigger the other workflows.

2023-08-30 18:23 UTC, joshdhart commented
> hey @joshdhart thanks for the PR! can you please run `clang-format` on the file? Once that check passes, that will make the CI trigger the other workflows.

@sharvilshah CI checks are now passing.

2023-08-31 14:39 UTC, sharvilshah commented
> > hey @joshdhart thanks for the PR! can you please run `clang-format` on the file? Once that check passes, that will make the CI trigger the other workflows.
> 
> @sharvilshah CI checks are now passing.

@joshdhart I have added this to the 5.10.0 milestone, and I will try and get this reviewed in a few days.

2023-09-18 15:41 UTC, joshdhart commented
> > > hey @joshdhart thanks for the PR! can you please run `clang-format` on the file? Once that check passes, that will make the CI trigger the other workflows.
> > 
> > 
> > @sharvilshah CI checks are now passing.
> 
> @joshdhart I have added this to the 5.10.0 milestone, and I will try and get this reviewed in a few days.

Any update on the review?

2023-09-22 08:22 UTC, sharvilshah approved these changes

2023-09-22 16:07 UTC, merged