Copy keychain files.
osquery/osquery pull request #8189
Opened 2023-11-10 22:51 UTC by getvictor

Fixes #7780

Updating `certificates` and `keychain_items` tables to make a copy of keychain files before working on them.
We hope that fixes the corruption of login keychains seen by some users.

The `keychain_acl` table does not work with copied keychains because copies fail authentication.

To submit a PR please make sure to follow the next steps:

- [ ] Read the `CONTRIBUTING.md` guide at the root of the repo.
- [ ] Ensure the code is formatted building the `format_check` target.  
      If it is not, then move the committed files to the git staging area,
      build the `format` target to format them, and then re-commit.
      [More information is available on the wiki](https://osquery.readthedocs.io/en/latest/development/building/#formatting-the-code).
- [x] Ensure your PR contains a single logical change.
- [ ] Ensure your PR contains tests for the changes you're submitting.
- [x] Describe your changes with as much detail as you can.
- [x] Link any issues this PR is related to.
- [ ] Remove the text above.

2023-11-10 23:05 UTC, getvictor commented on osquery/tables/system/darwin/certificates.mm
> +    // TODO: Add error handling/logging here.
@getvictor TODO

2023-11-10 23:05 UTC, getvictor commented on osquery/tables/system/darwin/keychain_items.cpp
> +  // TODO: Log error if needed.
@getvictor TODO

2023-11-10 23:11 UTC, zwass commented
Some testing related questions I'm curious about:

1) Were you able to reproduce the corruption issue and verify that it no longer reproduces with these changes?
2) Did you compare the results from this implementation with the results from the original table?
3) How does the performance of this implementation (using profile.py) compare to the performance of the original implementation? I imagine this will use more resources, but I don't have a great sense of how much more.

2023-11-11 12:10 UTC, sharvilshah reviewed
Hey @getvictor, thanks for taking a look into this, it's super appreciated! 

It's been a while since I looked into this, apologies if I am off-base. From what I recall: 
* The `SecKeychainOpen` set of APIs are deprecated -- these APIs do give us a complete view of keychain items, but are inherently prone to race conditions and keychain corruption on repeatedly calling these. I have only been partially successful in reproducing these, but repeatedly opening the keychain files in quick succession has led to corruption previously. 
* The newer APIs give a limited view of the keychain items, and are also slightly less performant.

I do think we do want a complete view of the keychain items, as that is very helpful. 

Instead of dealing with temporary copies of keychain files, what do you think of this alternative approach to gating the `SecKeychainOpen` calls? 

We could cache the result of this query along with the SHA/hash of the keychain file(s) internally on first query/cache miss. On subsequent calls, we can compare the hash of the keychain file on the filesystem and what we have cached and return the cached result or update our cache with `SecKeychainOpen` APIs and then return the result.

To me creating keychain copies in temp directories feels inherently weird -- osquery tries to not change state of the system and creating these temp keychain copies feels orthogonal. There can potentially be cases where we fail to cleanup if watchdog takes an action on the query, and these temp copies could also result in false positives on systems that monitor/alert on access to sensitive files.

Thoughts on this? 

PS: This would be a perfect agenda item for the office hours

2023-11-13 10:20 UTC, Smjert commented
> 
> Thoughts on this?
> 
> PS: This would be a perfect agenda item for the office hours

I don't have other alternatives, beyond what you suggested, and I also second the concern on the copy; not only it could cause noise in the monitoring, conceptually modify the system, but then that is an unmonitored (and maybe less protected?) copy of the keychain.

2023-11-13 20:58 UTC, getvictor commented
> Some testing related questions I'm curious about:
> 
> 1. Were you able to reproduce the corruption issue and verify that it no longer reproduces with these changes?
> 2. Did you compare the results from this implementation with the results from the original table?
> 3. How does the performance of this implementation (using profile.py) compare to the performance of the original implementation? I imagine this will use more resources, but I don't have a great sense of how much more.

1. I was not able to reproduce the corruption issue. So, I'm not 100% sure this fix will work.
2. Yes, I did a diff of the results -- they are identical.
3. For `certificates` profile of 10 rounds, the new approach is actually slightly faster:
```
 U:1  C:0  M:3  F:0  D:0  manual: utilization: 12.66 cpu_time: 0.12895289520000003 memory: 33559347.2 fds: 4.0 duration: 0.5284709215164185
 U:1  C:0  M:3  F:0  D:0  manual: utilization: 11.425 cpu_time: 0.11638463639999999 memory: 33269350.4 fds: 4.0 duration: 0.5258088350296021
```

For `keychain_items` profile of 10 rounds, the new approach is >50% faster:
```
 U:2  C:1  M:3  F:0  D:2  manual: utilization: 31.869999999999997 cpu_time: 0.48244730560000004 memory: 26024345.6 fds: 4.0 duration: 1.0270737648010253
 U:2  C:0  M:3  F:0  D:0  manual: utilization: 21.025 cpu_time: 0.2130715374 memory: 25812992.0 fds: 4.0 duration: 0.5274701833724975
```

2023-11-13 21:14 UTC, getvictor commented
> We could cache the result of this query along with the SHA/hash of the keychain file(s) internally on first query/cache miss. On subsequent calls, we can compare the hash of the keychain file on the filesystem and what we have cached and return the cached result or update our cache with `SecKeychainOpen` APIs and then return the result.

I have not seriously considered this option. It is not simple to implement and it does not guarantee to solve the keychain corruption issue.

The temp copies of the keychain files have the same permissions as the originals, so they should not be less secure. I agree that it is good to ensure the copies are deleted.

Any ideas how to ensure temp files are deleted due to watchdog?

2023-11-13 23:25 UTC, sharvilshah requested changes
> > We could cache the result of this query along with the SHA/hash of the keychain file(s) internally on first query/cache miss. On subsequent calls, we can compare the hash of the keychain file on the filesystem and what we have cached and return the cached result or update our cache with `SecKeychainOpen` APIs and then return the result.
> 
> I have not seriously considered this option. It is not simple to implement and it does not guarantee to solve the keychain corruption issue. 

It is perhaps not as simple to implement as creating copies of the keychain file(s), but all the building blocks are there. Is there something you need help with to get started? 

The only thing that would guarantee to solve the keychain corruption issue is Apple fixing this. 

> 1. I was not able to reproduce the corruption issue. So, I'm not 100% sure this fix will work.

I am not comfortable with file copies as the way to go for this, until we have at least explored/exhausted other potential solutions. 
> 
> The temp copies of the keychain files have the same permissions as the originals, so they should not be less secure. 

Though the copies are encrypted and have the same perms, we are potentially widening the attack surface area.  

> Any ideas how to ensure temp files are deleted due to watchdog?

I am not a hundred percent sure, but I don't think that watchdog does a kill, allowing us to cleanup resources. https://github.com/osquery/osquery/blob/master/osquery/core/watcher.h or https://github.com/osquery/osquery/blob/master/osquery/core/shutdown.h could be worth a look.

2023-11-14 23:21 UTC, getvictor commented
@sharvilshah I started a PR for the caching approach: https://github.com/osquery/osquery/pull/8192 I have 2 out of 3 tables working. Please take a look if you have any feedback.

2023-11-26 17:56 UTC, getvictor commented
Closing in favor of https://github.com/osquery/osquery/pull/8192

2023-11-26 17:56 UTC, closed without merging