Added cache for `keychain_acls` table.
osquery/osquery pull request #8192
Opened 2023-11-14 20:58 UTC by getvictor

#7780 
Adding a cache for macOS keychain file accesses.

The cache checks whether a keychain file has been modified by comparing the file's SHA256 hash. If the file has been modified, the cache also checks whether the file has been accessed recently. If it has been accessed within the configured interval, the old cached results are returned.

2023-11-15 21:48 UTC, getvictor commented on osquery/tables/system/tests/CMakeLists.txt
> +          osquery_utils_info
Not sure if `osquery_utils` and `osquery_utils_info` is needed here.

2023-11-21 21:01 UTC, zwass requested changes
This is mostly looking good to me. Minor changes requested.

I would like to manually verify I get the same results before and after this change but I'm currently blocked by #8196 (and working on resolving that).

2023-11-23 09:53 UTC, Smjert requested changes
Something to be careful about is that every table can be called concurrently, by a query via the scheduler and a query via the distributed/ad-hoc system.

Here the cache is global, so it would need to be thread safe.

2023-11-27 21:23 UTC, zwass commented
I definitely like the idea of updating the table documentation. The mutex work lgtm but I'll let @Smjert weigh in.

2023-11-28 11:50 UTC, Smjert commented
This is a bit of a drive by review: one thing I noticed is that putting the lock inside the cache itself, while it protects the cache data from corruption or half reads, the operation done in the table is not a transaction. You have to consider that the threads can stop at any point in between the read and write, and they can swap order.

What could happen is that two concurrent queries both initially read the cache and have no hit, so both go and try to read the keychain data from the file. But then the one that read the keychain for **first** (with the data less up to date) gets preempted and the one that came **second** is the one first writing into the cache; then when the first thread wakes up, it will overwrite the most recent data.

There's to say though that it's unlikely that something changes in the time that passes between the preemption of the thread and it's later wake up.

I don't know if you have already considered this; again it doesn't seems necessarily an issue from this quick review, but I thought I'd mention it.

2023-11-28 12:17 UTC, Smjert submitted a review, later dismissed

2023-11-28 13:07 UTC, Smjert commented
> I see that Stefano approved this, but I find myself confused about how the cache works. Do entries persist between queries? If so, do they expire? There's an access interval, which isn't quite the same as cache expiration.
> 
> If you have a reasonable story for those, I'm not this this PR needs to change. But a followup PR with some clear docs in the "wiki" would help.

Basically the cache has a copy of **all** the results (as if no constraint was applied) for each of the specified category here: https://github.com/osquery/osquery/pull/8192/files#diff-cbf1c8c0ddce99dc2309a7852b01cdd527797a808a0c1ad0aa4a231729bb8213R32

Each osquery table writes in one of the different categories, always substituting the whole thing.
So there's no way to continuosly increase the cache size because you're keeping old and new results.

But there's still the problem of deciding for how long to reuse the data (when to invalidate), and currently that's implemented with an interval.

This is my understanding for how this works.

2023-11-28 13:48 UTC, Smjert commented
> if the hash has changed and enough time has passed (keychain_access_interval) from the last keychain read, then we invalidate the cache and re-read the data from disk, otherwise we return the cached data.

With the further caveat that I expressed here: https://github.com/osquery/osquery/pull/8192#issuecomment-1829684795, where two queries could either find the cache empty or the hash file changed **and** enough time to have been passed, and both decide they need to access the keychain in close succession, not respecting the interval after the new, first access.

2023-11-28 20:22 UTC, getvictor commented
@Smjert Yes, if two threads miss in the cache at the same time, they will both access the keychain files and both write to the cache. It the keychain file was also modified during this, we can end up with:
1. Old hash pointing to old data.
2. Old hash pointing to new data.

In both cases, the data will remain there for the keychain_access_interval, and hash/data will be updated with a subsequent access. Since osquery will recover from this corner case situation, it doesn't seem like a huge concern.

@directionless I will add additional documentation to the Command Line Flags wiki in a separate PR.

2023-11-28 21:12 UTC, getvictor commented
Additional documentation added in PR https://github.com/osquery/osquery/pull/8205

2023-11-29 13:28 UTC, getvictor commented
@Smjert 
You're right. Here's the "correct" flow:
1. Thread1 reads cache, creates hash1
2. Keychain file modified
3. Thread1 reads keychain file <-- issue
4. Thread2 reads cache and creates hash2
5. Thread2 writes cache
6. Thread1 writes cache <-- bad data!

2023-11-29 13:40 UTC, getvictor commented
You're right -- I don't see how we can get new hash with old data unless the keychain file is modified twice. I think it is still worthwhile to limit access to 1 keychain table at a time.

2023-11-29 13:43 UTC, Smjert commented
> @Smjert You're right. Here's the "correct" flow:
> 
> 1. Thread1 reads cache, creates hash1
> 2. Keychain file modified
> 3. Thread1 reads keychain file <-- issue
> 4. Thread2 reads cache and creates hash2
> 5. Thread2 writes cache
> 6. Thread1 writes cache <-- bad data!

But in that case wouldn't Thread1 write the new results with the old hash, which is still reason for the next update interval to substitute those values (with the same ones).

Maybe I'm not on the same page on what you intend with "bad data" or "corrupted". Since I thought we were clear that it's possible to have all sorts of combinations of hash and results, but with both being written under lock and fully, there was no real corruption (where not all the results are saved and or there's literal memory corruption, with garbage data corrupting data structures and so on).

I think the real issue is if somehow a newer hash (corresponding to a newer state of the keychain) is being saved together with old results. This should not happen because, the hash is calculated first and hash + results are written in the cache together, so there's no way two threads can race and swap order between the hash and results write.

That been said again, I'm all for the more comprehensive (transaction) approach, which should simply remove these special cases and simplify the reasoning.

2023-12-13 12:12 UTC, directionless commented
@Smjert @zwass How does this look?

2023-12-13 18:54 UTC, zwass approved these changes
This lgtm. Thank you Victor! @Smjert please have a look soon otherwise I propose we merge this week.

2023-12-15 16:10 UTC, merged

2024-01-07 20:04 UTC, great944 commented
hello, while I understand the value of a cache for osquery when running as a service, I am curious if we have considered scenarios where the main use cases are from a command line? do we have a way to optout of caching ? our primary use case is to execute a query on the command line i.e. osqueryd.exe -S --json "select * from xyz" and we do not wish to activate any caching.

2024-01-08 21:20 UTC, directionless commented
Hi @great944 

The cache in this PR is specific to the macOS keychain related tables, and given the underlying corruption issues from the OS it would be a bad idea to disable it. That said, this PR also includes an option to disable it.

Can you share what your concerns are, and why you wouldn't want it for straight CLI usage?

2024-01-08 21:31 UTC, Smjert commented
Also keep into account that the cache would only work for multiple queries to the keychain tables done in the same command line execution, given that the cache is in memory only.
So sure, there might be a slight slowdown to create the cache at each execution, but if you have a single query to a keychain table, each execution will not use the cache.