Add `CHANGELOG.md` entry for 5.13.0
osquery/osquery pull request #8370
Opened 2024-07-10 11:08 UTC by lucasmrod

Ran the following to generate the changes:
```
go run ./cmd/release-notes -changelog /path/to/osquery/CHANGELOG.md -last 5.12.2 -new 5.13.0 > NEW.txt
```
And then edited manually by looking at https://github.com/osquery/osquery/compare/5.12.2...5.13.0.

2024-07-29 14:51 UTC, Smjert requested changes
Thanks for starting this.

It misses under Build:
https://github.com/osquery/osquery/pull/8308

Under Bug Fixes:
https://github.com/osquery/osquery/pull/8334

Under Documentation:
https://github.com/osquery/osquery/pull/8340
https://github.com/osquery/osquery/pull/8348

2024-07-29 14:51 UTC, Smjert commented on CHANGELOG.md
> +- Make fallthrough explicit in `sqlite_encoding.cpp` ([#8361](https://github.com/osquery/osquery/pull/8361))
I would move this under `Build` since it's just to not warn at compile time when enabling a certain warning flag.

2024-07-29 14:51 UTC, Smjert commented on CHANGELOG.md
> +- Docs: improve explanation of required columns ([#8365](https://github.com/osquery/osquery/pull/8365))
```suggestion
- Improve explanation of required columns ([#8365](https://github.com/osquery/osquery/pull/8365))
```

2024-07-29 14:51 UTC, Smjert commented on CHANGELOG.md
> +- ci: Update Linux Docker image to Ubuntu 20.04 ([#8369](https://github.com/osquery/osquery/pull/8369))
```suggestion
- Update Linux Docker image to Ubuntu 20.04 ([#8369](https://github.com/osquery/osquery/pull/8369))
```

2024-07-29 14:51 UTC, Smjert commented on CHANGELOG.md
> +- CI: Update macos builder to 14 and tester to 12 ([#8359](https://github.com/osquery/osquery/pull/8359))
```suggestion
- Update macos builder to 14 and tester to 12 ([#8359](https://github.com/osquery/osquery/pull/8359))
```

2024-07-29 14:51 UTC, Smjert commented on CHANGELOG.md
> +- Remove duplicated words ([#8336](https://github.com/osquery/osquery/pull/8336))
```suggestion
- Remove some duplicated words from code comments and strings ([#8336](https://github.com/osquery/osquery/pull/8336))
```

2024-08-01 04:02 UTC, zwass commented
@Smjert I made the changes you suggested besides for the 5.12.2 changelog entries which don't really seem necessary to me?

2024-09-10 19:45 UTC, zwass approved these changes

2024-09-10 19:45 UTC, merged