Add a try/catch to `fs::recursive_directory_iterator`
osquery/osquery pull request #8392
Opened 2024-08-02 00:28 UTC by directionless

Fixes #8391

Looking at our code, I notice that we call `fs::recursive_directory_iterator` in two places. One has a try/catch, one does not. The internet suggests some versions of boost have a bug that causes is_symlink to raise if there's no permissions. They reference https://svn.boost.org/trac/boost/ticket/4494 which doesn't exist any more

2024-08-02 09:13 UTC, Smjert requested changes
Good catch! It's possible to see the bug here: https://web.archive.org/web/20160804003617/https://svn.boost.org/trac/boost/ticket/4494, but that's for a pretty old version of boost, I would expect for that to have been fixed.

Either way the issue created and the crash shown there talks about `recursive_directory_iterator` causing the exception, but we are using all of the boost APIs with their exception throwing variant.
If instead we use the other constructor, it's possible for the API to register errors into a return value; I would use that instead of an exception, since exception throwing is pretty slow, and it's especially not ideal in a loop like this. 
You can see the various functions docs here: https://www.boost.org/doc/libs/1_77_0/libs/filesystem/doc/reference.html

Furthermore a Permission Denied is not totally unexpected or "exceptional", so it makes sense to handle it differently.

2024-08-02 12:17 UTC, directionless commented
> If instead we use the other constructor, it's possible for the API to register errors into a return value; I would use that instead of an exception, since exception throwing is pretty slow, and it's especially not ideal in a loop like this

I agree, but I'm not much of a c++ programmer. Is there an example I can borrow from?

2024-08-03 15:29 UTC, directionless commented
Cribbing from the internet, if I do this:
```
    boost::system::error_code ec;

    for (fs::recursive_directory_iterator it{path, ec}, end; it != end;
         it.increment(ec)) {
      LOG(WARNING) << "SEPH: examinging " << it->path() << "\n";
      if (fs::is_symlink(it->path())) {
        results.push_back(it->path().string());
      } else if (fs::is_directory(it->path())) {
        results.push_back(it->path().string());
      }
    }
```

It stops on the first permission denied error. Obviously not the behavior we want.

2024-08-03 20:44 UTC, directionless commented
As I understand it, there are a couple of things. The first issue, is that we want the non-throw form -- to get this, we pass in an error receiver. The second issue, is that short form of the for loop uses `++` which has causes an exception if the iterate is passed in, thus the 3 part `for` loop. 

I've also opted to pass in `fs::directory_options::skip_permission_denied` since otherwise the iteration stops on the first permission error.

I opted to ignore the errors, half because I didn't know how to read them, and half because all we'd do is `INFO` log them.

For my future self, these links had some okay explanations, and some possible helpers if we wanted to make a class for it. 
- https://stackoverflow.com/questions/73101565/how-to-use-recursive-directory-iterator-without-exceptions-in-c
- https://stackoverflow.com/questions/70382262/recursive-directory-iterators-skip-permission-denied-option-appears-to-be-ignor
- https://stackoverflow.com/questions/67776830/c-directory-item-iteration-without-exceptions

2024-08-09 15:32 UTC, Smjert submitted a review, later dismissed
Sorry for the delay, but yes passing the error_code to the constructor so that it can be set is what I meant.

But we have to do it to all the functions, otherwise other can still throw.

2024-08-09 15:32 UTC, Smjert commented on osquery/filesystem/filesystem.cpp
> +      if (fs::is_symlink(entry->path())) {
```suggestion
      if (fs::is_symlink(entry->path(), ec)) {
```

2024-08-09 15:32 UTC, Smjert commented on osquery/filesystem/filesystem.cpp
> +      } else if (fs::is_directory(entry->path())) {
```suggestion
      } else if (fs::is_directory(entry->path(), ec)) {
```

2024-08-09 15:32 UTC, Smjert commented on osquery/filesystem/filesystem.cpp
> +      if (fs::is_symlink(entry->path())) {
```suggestion
      if (fs::is_symlink(entry->path(), ec)) {
```

2024-08-09 15:32 UTC, Smjert commented on osquery/filesystem/filesystem.cpp
> +      } else if (fs::is_directory(entry->path())) {
```suggestion
      } else if (fs::is_directory(entry->path(), ec)) {
```

2024-08-10 12:30 UTC, Smjert commented on osquery/filesystem/filesystem.cpp
> +  if (path.empty() || !pathExists(path) || !fs::is_directory(path)) {
I missed this check here, so we should be moving the error code definition above this, and then pass `ec` as the second argument of `is_directory`.

2024-08-13 23:06 UTC, zwass approved these changes
LGTM. By my interpretation we should be getting the same semantics while skipping permission errors and avoiding throws.

2024-08-13 23:08 UTC, merged